# coding: utf-8

"""
Django settings for ilnurgi project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

import yaml

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'tts0qt$9)n&vwgupdl6gqd8sm4v!&tf+m3p=r03f=qrt4c2uyn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'gunicorn',

    'application',
    'metrics',

)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'application.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'application.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

DATABASE_MONGO = {
    'host': 'localhost',
    'port': '27017',
    'nginx_access_db_name': 'nginx_access',
    'cpu_average_db_name': 'cpu_average',
    'mem_average_db_name': 'mem_average',
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

settings_json = os.path.join(BASE_DIR, 'settings.json')

LOG_PATH = os.path.join(BASE_DIR, 'logs')

if os.path.exists(settings_json):
    globals().update(yaml.load(open(settings_json)))

parse_nginx_acces_log_path = os.path.join(LOG_PATH, 'nginx_access_parse_logs')
if not os.path.exists(parse_nginx_acces_log_path):
    os.makedirs(parse_nginx_acces_log_path)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'parse_nginx_access': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(parse_nginx_acces_log_path, 'log.log')
        },
        'console': {
            'class': 'logging.StreamHandler',
        }
    },
    'loggers': {
        'parse_nginx_access': {
            'level': 'DEBUG',
            'handlers': ['parse_nginx_access']
        }
    }
}

if DEBUG and 'console' in LOGGING['handlers']:
    LOGGING['loggers']['parse_nginx_access']['handlers'].append('console')
